name: "deploy"

on:
  push:
    paths:
      - ".github/workflows/**"
      - "src/**"
      - "build.gradle.kts"
      - "settings.gradle.kts"
      - "Dockerfile"
    branches:
      - "main"
      - "app1"
      - "app2"
      - "app3"
      - "app4"
      - "app5"
      - "app6"
      - "app7"

env:
  APP_NAME: grr-test
  APP_COUNT: 7  # 배포할 app 개수 (app1 ~ app7)

jobs:
  makeTagAndRelease:
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.create_tag.outputs.new_tag }}
    steps:
      - uses: actions/checkout@v4

      - name: Create Tag
        id: create_tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.create_tag.outputs.new_tag }}
          release_name: Release ${{ steps.create_tag.outputs.new_tag }}
          body: ${{ steps.create_tag.outputs.changelog }}
          draft: false
          prerelease: false

  buildImageAndPush:
    name: 도커 이미지 빌드와 푸시
    needs: makeTagAndRelease
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Docker Buildx 설치
        uses: docker/setup-buildx-action@v2

      - name: 레지스트리 로그인
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: set lower case owner name
        run: echo "OWNER_LC=${OWNER,,}" >> $GITHUB_ENV
        env:
          OWNER: "${{ github.repository_owner }}"

      - name: application-secret.yml 생성
        env:
          APPLICATION_SECRET: ${{ secrets.APPLICATION_SECRET_YML }}
        run: echo "$APPLICATION_SECRET" > src/main/resources/application-secret.yml

      - name: 빌드 앤 푸시
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          cache-from: type=registry,ref=ghcr.io/${{ env.OWNER_LC }}/${{ env.APP_NAME }}:cache-${{ github.ref_name }}
          cache-to: type=registry,ref=ghcr.io/${{ env.OWNER_LC }}/${{ env.APP_NAME }}:cache-${{ github.ref_name }},mode=max
          tags: |
            ghcr.io/${{ env.OWNER_LC }}/${{ env.APP_NAME }}:${{ needs.makeTagAndRelease.outputs.tag_name }},
            ghcr.io/${{ env.OWNER_LC }}/${{ env.APP_NAME }}:latest

  deploy:
    name: 쿠버네티스 배포
    needs: [ makeTagAndRelease, buildImageAndPush ]
    runs-on: ubuntu-latest
    steps:
      - uses: azure/k8s-set-context@v2
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: set lower case owner name 및 변수 설정
        run: |
          echo "OWNER_LC=${OWNER,,}" >> $GITHUB_ENV
          echo "BRANCH_NAME=${GITHUB_REF_NAME}" >> $GITHUB_ENV
          echo "APP_COUNT=7" >> $GITHUB_ENV  # <-- 여기 직접 설정
        env:
          OWNER: "${{ github.repository_owner }}"
          GITHUB_REF_NAME: ${{ github.ref_name }}

      - name: 이미지 업데이트 및 출력
        env:
          IMAGE_TAG: ghcr.io/${{ env.OWNER_LC }}/${{ env.APP_NAME }}:${{ needs.makeTagAndRelease.outputs.tag_name }}
        run: |
          if [ "$BRANCH_NAME" = "main" ]; then
            for i in $(seq 1 "$APP_COUNT"); do
              DEPLOYMENT_NAME="${APP_NAME}-app${i}-deployment"
              CONTAINER_NAME="${APP_NAME}-app${i}"
              echo "🔍 Checking $DEPLOYMENT_NAME ..."
              if kubectl get deployment "$DEPLOYMENT_NAME" > /dev/null 2>&1; then
                echo "✅ $DEPLOYMENT_NAME exists. Updating image..."
                kubectl set image deployment/"$DEPLOYMENT_NAME" "$CONTAINER_NAME"="$IMAGE_TAG"
              else
                echo "⚠️  $DEPLOYMENT_NAME not found. Skipping."
              fi
            done
          else
            DEPLOYMENT_NAME="${APP_NAME}-${BRANCH_NAME}-deployment"
            CONTAINER_NAME="${APP_NAME}-${BRANCH_NAME}"
            echo "🔍 Checking $DEPLOYMENT_NAME ..."
            if kubectl get deployment "$DEPLOYMENT_NAME" > /dev/null 2>&1; then
              echo "✅ $DEPLOYMENT_NAME exists. Updating image..."
              kubectl set image deployment/"$DEPLOYMENT_NAME" "$CONTAINER_NAME"="$IMAGE_TAG"
            else
              echo "⚠️  $DEPLOYMENT_NAME not found. Skipping."
            fi
          fi
